name: .NET

on:
  push:
    branches: [ master ]
    tags: 
      - 'v*.*.*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        tag=${{ github.ref:10 }}
        target=win-x64
        release_name="App-$tag-$target
        dotnet publish -c Release -o "$release_name"
        7z a -tzip "${release_name}.zip" "./${release_name}/*"
        rm -r "$release_name"
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "App*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
