name: .NET

on:
  push:
    branches: [ master ]
    tags: 
      - 'v*.*.*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Vars
      id: vars
      run: |
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Publish
      env:
        SOURCE_TAG: ${{ steps.vars.outputs.SOURCE_TAG }}
      if: startsWith(github.ref, 'refs/tags/')      
      run: |
        tag=$SOURCE_TAG
        target=win-x64
        release_name="App-$tag-$target"
        dotnet publish -r $target -c Release -o "$release_name" --self-contained false -p:PublishSingleFile=true
        7z a -tzip "${release_name}.zip" "./${release_name}/*"
        rm -r "$release_name"
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "App*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
